const app=document.querySelector('#app');
const state={step:'invite',no:0,time:'19:00',place:''};
const places=[{id:'bezerra',name:'Espetaria do Bezerra Praia',address:'Rua Praia de Genipabú, 2105 · Ponta Negra',note:'Espetinhos para começar o nosso rolê.',source:'https://espetariadobezerrapraia.ola.click/'},{id:'pepeto',name:'Seu Pepeto · Ponta Negra',address:'Av. Praia de Ponta Negra, 9076',note:'Mais uma opção para um date com espetinho.',source:'https://www.tripadvisor.com.br/Restaurant_Review-g303518-d23780193-Reviews-Seu_Pepeto_Ponta_Negra-Natal_State_of_Rio_Grande_do_Norte.html'}];
function go(step){state.step=step;render();document.querySelector('h1')?.focus({preventScroll:true})}
function celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<20;i++){const el=document.createElement('span');el.className='burst';el.textContent=['♥','💕','✦'][i%3];el.style.setProperty('--x',`${Math.random()*96}%`);el.style.animationDelay=`${Math.random()*.5}s`;document.body.append(el);setTimeout(()=>el.remove(),3200)}}
function decline(){state.no++;const b=document.querySelector('#no');if(state.no===3){b.remove();document.querySelector('#hint').textContent='O universo tá dando sinais 👀';document.querySelector('#yes').focus();return}b.textContent=state.no===1?'jura, vey?':'POR FAVOR';b.classList.add('moved');placeNo()}
function placeNo(){const b=document.querySelector('#no');if(!b?.classList.contains('moved'))return;const margin=18;const w=document.documentElement.clientWidth,h=window.innerHeight;b.style.left=state.no===1?`${Math.max(margin,w-b.offsetWidth-margin)}px`:`${margin}px`;b.style.top=state.no===1?`${margin}px`:`${Math.max(margin,h-b.offsetHeight-30)}px`}
window.addEventListener('resize',placeNo);
function render(){let html='';if(state.step==='invite')html=`<img class="art" src="heart.png" alt="Um coração fazendo carinha de por favor"><div class="eyebrow">EI, VOCÊ.</div><h1 tabindex="-1">Bora um date<br><em>comigo?</em></h1><p>Um churrasquinho, uns drinks<br>e eu tentando te impressionar.</p><div class="actions"><button class="primary" id="yes">SIM ♥</button>${state.no<3?`<button class="secondary" id="no">${['NÃO','jura, vey?','POR FAVOR'][state.no]}</button>`:''}</div><p class="small" id="hint" aria-live="polite">${state.no===3?'O universo tá dando sinais 👀':'Prometo dividir a última batatinha.'}</p>`;
if(state.step==='yes')html=`<span class="emoji" aria-hidden="true">😏💘</span><div class="eyebrow">EU SABIA. (MENTIRA, TAVA NERVOSO.)</div><h1 tabindex="-1">Você disse<br><em>sim mesmo?</em></h1><p>Pronto. Já tô sorrindo igual besta.<br>Agora só faltam os detalhes.</p><button class="primary" id="next">Bora marcar →</button>`;
if(state.step==='time')html=`<div class="eyebrow">01 / O HORÁRIO</div><h1 tabindex="-1">Amanhã tem<br><em>a gente.</em></h1><div class="date"><strong>25</strong><span><b>Sexta-feira</b>setembro de 2026<br>25/09/2026</span></div><form id="time-form"><label class="time" for="time">Que horas você tá livre?<input id="time" type="time" required value="${state.time}"></label><button class="primary">Agora, o lugar →</button></form><button class="back" id="back">← Voltar</button>`;
if(state.step==='place')html=`<div class="eyebrow">02 / O LUGAR</div><h1 tabindex="-1">Onde vai ser<br><em>nosso rolê?</em></h1><p>Churrasquinho + drinks + você.<br>Ponta Negra, Natal · ${state.time}</p><form id="place-form"><div class="places">${places.map(p=>`<label class="place"><input type="radio" name="place" value="${p.id}" required ${state.place===p.id?'checked':''}><span><strong>${p.name}</strong><small>${p.address}</small><small>${p.note}</small></span></label>`).join('')}</div><button class="primary">Fechou esse date ♥</button></form><p class="small">A gente confere os drinks e o funcionamento antes de ir.</p><details class="sources"><summary>Conferir os locais</summary>${places.map(p=>`<a href="${p.source}" target="_blank" rel="noopener noreferrer">${p.name}</a>`).join('<br>')}</details><button class="back" id="back">← Mudar horário</button>`;
if(state.step==='done'){const p=places.find(p=>p.id===state.place);html=`<span class="emoji" aria-hidden="true">🥂</span><div class="eyebrow">TÁ COMBINADO!</div><h1 tabindex="-1">Você, eu<br><em>e um date.</em></h1><div class="ticket"><div><small>Quando</small><b>Sexta, 25/09/2026 · ${state.time}</b></div><div><small>Onde</small><b>${p.name}</b><p class="small" style="margin:6px 0 0">${p.address}</p></div><div><small>O plano</small><b>Churrasquinho & uns drinks ♥</b></div></div><p>Agora me manda um print.<br>Eu cuido da ansiedade até lá.</p><a class="primary" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.name+' '+p.address+' Natal RN')}" target="_blank" rel="noopener noreferrer">Ver o lugar no mapa ↗</a><button class="back" id="back">← Trocar o lugar</button><p class="small">Só nosso combinado. Nenhuma reserva foi feita.</p>`}
app.innerHTML=`<section>${html}</section>`;
document.querySelector('#yes')?.addEventListener('click',()=>{go('yes');celebrate()});document.querySelector('#no')?.addEventListener('click',decline);if(state.step==='invite'&&state.no>0&&state.no<3){document.querySelector('#no').classList.add('moved');placeNo()}
document.querySelector('#next')?.addEventListener('click',()=>go('time'));
document.querySelector('#time-form')?.addEventListener('submit',e=>{e.preventDefault();state.time=document.querySelector('#time').value;go('place')});
document.querySelector('#place-form')?.addEventListener('submit',e=>{e.preventDefault();state.place=new FormData(e.target).get('place');go('done');celebrate()});
document.querySelector('#back')?.addEventListener('click',()=>go(({time:'yes',place:'time',done:'place'})[state.step]));}
render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_date_plan',description:'Read the current date invitation step and chosen time and place. No booking is made.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...state,date:'2026-09-25',place:places.find(p=>p.id===state.place)?.name||null})})).catch(()=>{})}catch{}}
